import { Theme } from "@radix-ui/themes";
import { Inter } from "next/font/google";

// contexts
import { ToastProvider } from "@/context/ToastContext";

// components
import { Initiator } from "./layout.client";

// types
import type { Metadata } from "next";

// styles
import "@radix-ui/themes/styles.css";
import "./globals.css";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
});

// meta
export const metadata: Metadata = {
	title: "WarehouseApp",
	description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<Theme appearance="light" accentColor="amber" grayColor="gray" panelBackground="translucent" radius="medium">
					<ToastProvider>
						<Initiator>{children}</Initiator>
					</ToastProvider>
				</Theme>
			</body>
		</html>
	);
}
